//! Regenerate `examples/polyglot/generated/`: the `Order` schema bytes, the
//! schema fingerprint, the six-row fixture, and the per-language generated
//! constant files the Quick Start and native-plugin builds compile in.
//!
//! The six polyglot stages no longer consume these constants — each derives
//! its own schema in its own language — but `cargo xtask quickstart` and
//! `cargo xtask plugins` still do, so the emitter lives on as its own example
//! rather than a subcommand of the polyglot driver.
//!
//! ```bash
//! cargo run -p saci-service --features wasm --example polyglot_schema_emit -- emit
//! ```

use std::fs;
use std::path::PathBuf;
use std::sync::Arc;

use arrow_ipc::writer::StreamWriter;
use arrow_schema::{DataType, Field, Schema};
use saci_service::component::Component;
use saci_service::dataset::Dataset;

/// Workspace root, derived from this crate's manifest dir so the example
/// behaves identically no matter which directory `cargo run` was invoked from.
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root above crates/saci-service")
        .to_path_buf()
}

fn generated_dir() -> PathBuf {
    workspace_root().join("examples/polyglot/generated")
}

/// Header stamped into every generated source file, in the target language's
/// comment syntax.
const GENERATED_BY: &str = "@generated by `cargo run -p saci-service --features wasm --example polyglot_schema_emit -- emit` — do not edit.";

/// One order, in the shape every polyglot stage reads and writes. Field order
/// is load-bearing: it feeds the schema fingerprint and the buffer walk the
/// SDK codecs perform.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq)]
struct Order {
    id: i64,
    region: String,
    currency: String,
    amount: f64,
    valid: bool,
    usd_amount: f64,
    usd_amount_display: String,
    risk_score: f64,
    flagged: bool,
    fee: f64,
    review_tier: i64,
    settlement: String,
}

impl Component for Order {
    fn name() -> &'static str {
        "Order"
    }

    fn schema() -> Arc<Schema> {
        Arc::new(Schema::new(vec![
            Field::new("id", DataType::Int64, false),
            Field::new("region", DataType::Utf8, false),
            Field::new("currency", DataType::Utf8, false),
            Field::new("amount", DataType::Float64, false),
            Field::new("valid", DataType::Boolean, false),
            Field::new("usd_amount", DataType::Float64, false),
            Field::new("usd_amount_display", DataType::Utf8, false),
            Field::new("risk_score", DataType::Float64, false),
            Field::new("flagged", DataType::Boolean, false),
            Field::new("fee", DataType::Float64, false),
            Field::new("review_tier", DataType::Int64, false),
            Field::new("settlement", DataType::Utf8, false),
        ]))
    }
}

impl Order {
    /// Construct an input row with every derived column zeroed.
    fn seed(id: i64, region: &str, currency: &str, amount: f64) -> Self {
        Self {
            id,
            region: region.to_string(),
            currency: currency.to_string(),
            amount,
            valid: false,
            usd_amount: 0.0,
            usd_amount_display: String::new(),
            risk_score: 0.0,
            flagged: false,
            fee: 0.0,
            review_tier: 0,
            settlement: String::new(),
        }
    }
}

/// The six-row fixture every polyglot verification path uses.
fn fixture_rows() -> Vec<Order> {
    vec![
        Order::seed(1, "emea", "EUR", 100.0),
        Order::seed(2, "emea", "GBP", -5.0),
        Order::seed(3, "apac", "JPY", 1_000_000.0),
        Order::seed(4, "amer", "USD", 60_000.0),
        Order::seed(5, "emea", "EUR", 0.0),
        Order::seed(6, "apac", "USD", 20_000.0),
    ]
}

/// A dataset with only `Order` registered: the source of both the fingerprint
/// and the fixture.
fn order_dataset() -> Dataset {
    let mut dataset = Dataset::new();
    dataset
        .register_component::<Order>()
        .expect("register Order");
    dataset
}

/// The 8-char lowercase hex fingerprint that WIT
/// `pipeline-descriptor.schema-fingerprint` carries for a pipeline registering
/// exactly `Order`.
fn order_fingerprint() -> String {
    format!("{:08x}", order_dataset().schemas().fingerprint())
}

/// Schema-only Arrow IPC stream for `Order`: a `StreamWriter` opened on the
/// schema and finished with no batches.
fn order_schema_ipc() -> Vec<u8> {
    let mut buf: Vec<u8> = Vec::new();
    let mut writer = StreamWriter::try_new(&mut buf, &Order::schema()).expect("open schema writer");
    writer.finish().expect("finish schema writer");
    buf
}

/// Standard base64 with `=` padding (RFC 4648 §4). Hand-rolled so the example
/// stays dependency-free; it runs once per `emit`, on ~700 bytes.
fn base64(bytes: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let b = [
            chunk[0],
            chunk.get(1).copied().unwrap_or(0),
            chunk.get(2).copied().unwrap_or(0),
        ];
        out.push(TABLE[(b[0] >> 2) as usize] as char);
        out.push(TABLE[((b[0] & 0x03) << 4 | b[1] >> 4) as usize] as char);
        out.push(if chunk.len() > 1 {
            TABLE[((b[1] & 0x0f) << 2 | b[2] >> 6) as usize] as char
        } else {
            '='
        });
        out.push(if chunk.len() > 2 {
            TABLE[(b[2] & 0x3f) as usize] as char
        } else {
            '='
        });
    }
    out
}

fn emit() -> Result<(), Box<dyn std::error::Error>> {
    let dir = generated_dir();
    fs::create_dir_all(&dir)?;

    let schema_ipc = order_schema_ipc();
    let fingerprint = order_fingerprint();
    let b64 = base64(&schema_ipc);

    let rows = fixture_rows();
    let mut dataset = order_dataset();
    dataset.append::<Order>(&rows)?;
    let mut fixture: Vec<u8> = Vec::new();
    dataset.write_ipc(&mut fixture)?;

    let json = serde_json::to_string_pretty(&rows)?;

    let go = format!(
        "// {GENERATED_BY}\n\npackage export_saci_pipeline_pipeline\n\n\
         // OrderSchemaIPCBase64 is the canonical `Order` Arrow IPC schema-message\n\
         // stream, base64-encoded. Decoded once at package init.\n\
         const OrderSchemaIPCBase64 = \"{b64}\"\n\n\
         // OrderFingerprint is the schema fingerprint the host expects in\n\
         // pipeline-descriptor.schema-fingerprint.\n\
         const OrderFingerprint = \"{fingerprint}\"\n"
    );
    let py = format!(
        "# {GENERATED_BY}\n\n\
         #: Canonical `Order` Arrow IPC schema-message stream, base64-encoded.\n\
         ORDER_SCHEMA_IPC_BASE64 = \"{b64}\"\n\n\
         #: Schema fingerprint reported in pipeline-descriptor.schema-fingerprint.\n\
         ORDER_FINGERPRINT = \"{fingerprint}\"\n"
    );
    let ts = format!(
        "// {GENERATED_BY}\n\n\
         /** Canonical `Order` Arrow IPC schema-message stream, base64-encoded. */\n\
         export const ORDER_SCHEMA_IPC_BASE64: string = \"{b64}\";\n\n\
         /** Schema fingerprint reported in pipeline-descriptor.schema-fingerprint. */\n\
         export const ORDER_FINGERPRINT: string = \"{fingerprint}\";\n"
    );
    let kt = format!(
        "// {GENERATED_BY}\n\n\
         package impl\n\n\
         /** Canonical `Order` Arrow IPC schema-message stream, base64-encoded. */\n\
         const val ORDER_SCHEMA_IPC_BASE64: String =\n    \"{b64}\"\n\n\
         /** Schema fingerprint reported in pipeline-descriptor.schema-fingerprint. */\n\
         const val ORDER_FINGERPRINT: String = \"{fingerprint}\"\n"
    );
    let cs = format!(
        "// {GENERATED_BY}\n\n\
         namespace PolyglotTier;\n\n\
         internal static class SchemaGen\n{{\n\
         \x20   /// <summary>Canonical `Order` Arrow IPC schema-message stream, base64-encoded.</summary>\n\
         \x20   internal const string OrderSchemaIpcBase64 =\n\
         \x20       \"{b64}\";\n\n\
         \x20   /// <summary>Schema fingerprint reported in pipeline-descriptor.schema-fingerprint.</summary>\n\
         \x20   internal const string OrderFingerprint = \"{fingerprint}\";\n\
         }}\n"
    );

    let files: [(&str, &[u8]); 9] = [
        ("order_schema.ipc", &schema_ipc),
        ("order_fingerprint.txt", fingerprint.as_bytes()),
        ("fixture_input.saci", &fixture),
        ("fixture_input.json", json.as_bytes()),
        ("schema_gen.go", go.as_bytes()),
        ("schema_gen.py", py.as_bytes()),
        ("schema_gen.ts", ts.as_bytes()),
        ("SchemaGen.kt", kt.as_bytes()),
        ("SchemaGen.cs", cs.as_bytes()),
    ];

    for (name, bytes) in files {
        let path = dir.join(name);
        fs::write(&path, bytes)?;
        println!("wrote {} ({} bytes)", path.display(), bytes.len());
    }

    println!("\nOrder fingerprint: {fingerprint}");
    println!("Order schema IPC:  {} bytes", schema_ipc.len());
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    match std::env::args().nth(1).as_deref() {
        Some("emit") => emit(),
        other => {
            eprintln!("usage: polyglot_schema_emit emit\n(unknown argument: {other:?})");
            std::process::exit(2);
        }
    }
}
