//! Generate the cross-language conformance corpus for the SACI Arrow IPC wire
//! format.
//!
//! ```bash
//! cargo run -p saci-service --features conformance --example conformance_vectors -- emit
//! ```
//!
//! Output lands in `packages/arrow-ipc-conformance/`: one `manifest.json` and
//! one `.saci` file per case. Every codec under `packages/arrow-ipc-*` runs the
//! corpus, so the five agree on exactly which streams are valid and which are
//! not.
//!
//! # How the malformed vectors are made
//!
//! Each one is a surgical mutation of a real `Dataset::write_ipc` stream, not a
//! hand-forged flatbuffer. A hand-forged stream can drift from what arrow-rs
//! actually emits, and then a codec that rejects it looks correct while failing
//! on real traffic. Mutating real output keeps every vector one edit away from a
//! stream the reference writer produced.
//!
//! The one exception is `compressed_batch`, which is re-encoded through
//! arrow-rs with LZ4 enabled. That needs the `conformance` feature, which turns
//! on `arrow-ipc/lz4` here and nowhere else: a normal SACI build cannot write a
//! compressed batch, and must reject one.
//!
//! # Reason codes
//!
//! A rejected case carries a language-neutral `reason`. Error text differs by
//! language on purpose, so a codec's harness maps the reason to whatever
//! substring its own message uses. The reason set is the contract; the wording
//! is local.

use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use arrow_array::RecordBatch;
use arrow_ipc::reader::StreamReader;
use arrow_ipc::writer::{IpcWriteOptions, StreamWriter};
use arrow_ipc::{CompressionType, MetadataVersion};
use arrow_schema::{DataType, Field, Schema};
use saci_core::Dataset;
use saci_core::component::Component;
use serde_json::{Value, json};

const GENERATED_BY: &str = "@generated by `cargo run -p saci-service --features conformance --example conformance_vectors -- emit`";

/// Arrow `MessageHeader` union discriminants.
const HEADER_SCHEMA: u8 = 1;
const HEADER_DICTIONARY_BATCH: u8 = 2;
const HEADER_RECORD_BATCH: u8 = 3;

// ---------------------------------------------------------------------------
// the Order component
//
// Every vector is a mutation of a real `Dataset::write_ipc` stream of this
// component, so these twelve fields are the shape each codec under
// `packages/arrow-ipc-*` decodes when it runs the corpus. Field order is
// load-bearing twice over: it feeds the schema fingerprint recorded in the
// manifest, and it fixes the node and buffer order the mutations below index
// into.
//
// The definition is inlined rather than shared with the polyglot example. The
// corpus is checked in, so the generator has to build on its own; a schema
// crate it depended on would make regenerating the corpus contingent on that
// crate existing.
// ---------------------------------------------------------------------------

/// One order, in the shape the conformance corpus carries.
#[derive(serde::Serialize, serde::Deserialize, Clone, Debug, PartialEq)]
pub struct Order {
    /// Stable row identity.
    pub id: i64,
    /// Originating region (`emea` / `apac` / `amer`).
    pub region: String,
    /// ISO currency code of `amount`.
    pub currency: String,
    /// Order amount in `currency`.
    pub amount: f64,
    /// Whether the order passed validation.
    pub valid: bool,
    /// `amount` converted to USD, or `0.0` when invalid.
    pub usd_amount: f64,
    /// `usd_amount` rendered for display. The second variable-width column,
    /// and the reason the `variable_width_write` vector has a sibling type to
    /// address.
    pub usd_amount_display: String,
    /// `usd_amount / risk_threshold`.
    pub risk_score: f64,
    /// `risk_score >= 1.0`.
    pub flagged: bool,
    /// `usd_amount` times the region's rate, or `0.0` when invalid.
    pub fee: f64,
    /// `0` clear, `1` manual review, `2` escalated.
    pub review_tier: i64,
    /// `REJECTED` / `HOLD` / `REVIEW` / `SETTLED`.
    pub settlement: String,
}

impl Component for Order {
    fn name() -> &'static str {
        "Order"
    }

    fn schema() -> Arc<Schema> {
        Arc::new(Schema::new(vec![
            Field::new("id", DataType::Int64, false),
            Field::new("region", DataType::Utf8, false),
            Field::new("currency", DataType::Utf8, false),
            Field::new("amount", DataType::Float64, false),
            Field::new("valid", DataType::Boolean, false),
            Field::new("usd_amount", DataType::Float64, false),
            Field::new("usd_amount_display", DataType::Utf8, false),
            Field::new("risk_score", DataType::Float64, false),
            Field::new("flagged", DataType::Boolean, false),
            Field::new("fee", DataType::Float64, false),
            Field::new("review_tier", DataType::Int64, false),
            Field::new("settlement", DataType::Utf8, false),
        ]))
    }
}

impl Order {
    /// An input row with every derived column zeroed.
    fn seed(id: i64, region: &str, currency: &str, amount: f64) -> Self {
        Self {
            id,
            region: region.to_string(),
            currency: currency.to_string(),
            amount,
            valid: false,
            usd_amount: 0.0,
            usd_amount_display: String::new(),
            risk_score: 0.0,
            flagged: false,
            fee: 0.0,
            review_tier: 0,
            settlement: String::new(),
        }
    }
}

/// The six rows the baseline vector carries.
///
/// The same fixture the polyglot example seeds, so a codec's conformance suite
/// and its polyglot stage read identical input columns.
fn fixture_rows() -> Vec<Order> {
    vec![
        Order::seed(1, "emea", "EUR", 100.0),
        Order::seed(2, "emea", "GBP", -5.0),
        Order::seed(3, "apac", "JPY", 1_000_000.0),
        Order::seed(4, "amer", "USD", 60_000.0),
        Order::seed(5, "emea", "EUR", 0.0),
        Order::seed(6, "apac", "USD", 20_000.0),
    ]
}

// ---------------------------------------------------------------------------
// flatbuffer navigation
//
// Only enough to find a value and overwrite it in place. Every helper returns
// an absolute offset into the slice it was handed.
// ---------------------------------------------------------------------------

/// Follow the root uoffset at `at` to the table it points at.
fn root_table(buf: &[u8], at: usize) -> usize {
    let rel = i32::from_le_bytes(buf[at..at + 4].try_into().unwrap());
    at + rel as usize
}

/// Absolute offset of `table`'s vtable.
fn vtable(buf: &[u8], table: usize) -> usize {
    let back = i32::from_le_bytes(buf[table..table + 4].try_into().unwrap());
    table - back as usize
}

/// Absolute offset of field `id`'s value inside `table`, or `None` when the
/// field is absent.
fn field(buf: &[u8], table: usize, id: usize) -> Option<usize> {
    let vt = vtable(buf, table);
    let vt_len = u16::from_le_bytes(buf[vt..vt + 2].try_into().unwrap()) as usize;
    let slot = 4 + id * 2;
    if slot + 2 > vt_len {
        return None;
    }
    let rel = u16::from_le_bytes(buf[vt + slot..vt + slot + 2].try_into().unwrap()) as usize;
    if rel == 0 { None } else { Some(table + rel) }
}

/// Resolve a vector field to `(element_start, count)`.
fn vector(buf: &[u8], table: usize, id: usize) -> Option<(usize, usize)> {
    let at = field(buf, table, id)?;
    let rel = u32::from_le_bytes(buf[at..at + 4].try_into().unwrap()) as usize;
    let vec_at = at + rel;
    let count = u32::from_le_bytes(buf[vec_at..vec_at + 4].try_into().unwrap()) as usize;
    Some((vec_at + 4, count))
}

/// One Arrow IPC message inside a segment.
struct Message {
    /// Offset of the continuation marker, relative to the segment body.
    start: usize,
    body_len: i64,
    header_type: u8,
    /// Offset of the message table, relative to the segment body.
    table: usize,
    /// Offset just past this message, relative to the segment body.
    end: usize,
}

/// One length-prefixed segment.
struct Segment {
    /// Offset of the u32 length prefix, absolute in the stream.
    prefix: usize,
    /// Offset of the segment body, absolute in the stream.
    body: usize,
    len: usize,
    messages: Vec<Message>,
}

fn align8(n: i64) -> usize {
    ((n + 7) & !7) as usize
}

/// Walk the stream into segments and their messages.
fn parse_framing(stream: &[u8]) -> Vec<Segment> {
    let mut segments = Vec::new();
    let mut pos = 0usize;

    loop {
        let len = u32::from_le_bytes(stream[pos..pos + 4].try_into().unwrap()) as usize;
        if len == 0 {
            break;
        }
        let body = pos + 4;
        let seg = &stream[body..body + len];

        let mut messages = Vec::new();
        let mut mp = 0usize;
        while mp + 8 <= seg.len() {
            let cont = u32::from_le_bytes(seg[mp..mp + 4].try_into().unwrap());
            assert_eq!(cont, 0xFFFF_FFFF, "expected a continuation marker at {mp}");
            let metadata_len = u32::from_le_bytes(seg[mp + 4..mp + 8].try_into().unwrap()) as usize;
            if metadata_len == 0 {
                // End-of-stream marker.
                mp += 8;
                continue;
            }
            let meta_start = mp + 8;
            let table = root_table(seg, meta_start);
            let header_type = field(seg, table, 1).map_or(0, |at| seg[at]);
            let body_len = field(seg, table, 3).map_or(0, |at| {
                i64::from_le_bytes(seg[at..at + 8].try_into().unwrap())
            });
            let end = meta_start + metadata_len + align8(body_len);
            messages.push(Message {
                start: mp,
                body_len,
                header_type,
                table,
                end,
            });
            mp = end;
        }

        segments.push(Segment {
            prefix: pos,
            body,
            len,
            messages,
        });
        pos = body + len;
    }

    segments
}

/// The `RecordBatch` header table of a message, relative to the segment body.
fn record_batch_table(seg: &[u8], message: &Message) -> usize {
    let header_at = field(seg, message.table, 2).expect("Message.header is required");
    let rel = u32::from_le_bytes(seg[header_at..header_at + 4].try_into().unwrap()) as usize;
    header_at + rel
}

// ---------------------------------------------------------------------------
// case assembly
// ---------------------------------------------------------------------------

struct Corpus {
    dir: PathBuf,
    cases: Vec<Value>,
    /// Reject vectors the Rust host reader also refuses. Informational: the
    /// codecs are deliberately stricter than arrow-rs in places, so a vector
    /// arrow-rs accepts is not a broken vector.
    host_rejects: usize,
    host_accepts: Vec<String>,
}

/// Whether the Rust host reader takes this stream.
///
/// Informational, not a safety check: the five codecs under
/// `packages/arrow-ipc-*` are deliberately stricter than arrow-rs in places
/// (see `Corpus::host_accepts` below), so a vector arrow-rs accepts here is
/// not a broken vector. `Dataset::read_ipc` itself is panic-safe — it runs
/// the arrow-rs decode behind `catch_unwind` and turns a malformed buffer
/// span into `Err` — so this needs no unwind handling of its own.
fn host_reader_accepts(bytes: &[u8]) -> bool {
    Dataset::read_ipc(&mut &bytes[..]).is_ok()
}

impl Corpus {
    fn reject(&mut self, name: &str, reason: &str, note: &str, bytes: Vec<u8>) {
        let file = format!("vectors/{name}.saci");
        fs::write(self.dir.join(&file), &bytes).expect("write vector");
        if host_reader_accepts(&bytes) {
            self.host_accepts.push(name.to_string());
        } else {
            self.host_rejects += 1;
        }
        self.cases.push(json!({
            "name": name,
            "vector": file,
            "expect": "reject",
            "reason": reason,
            "note": note,
        }));
    }

    /// A case that parses but whose named operation must be refused.
    fn reject_op(&mut self, name: &str, reason: &str, note: &str, vector: &str, op: Value) {
        self.cases.push(json!({
            "name": name,
            "vector": vector,
            "expect": "reject",
            "reason": reason,
            "note": note,
            "op": op,
        }));
    }

    fn accept(&mut self, name: &str, note: &str, bytes: Vec<u8>, expect: Value) -> String {
        let file = format!("vectors/{name}.saci");
        fs::write(self.dir.join(&file), &bytes).expect("write vector");
        self.cases.push(json!({
            "name": name,
            "vector": file,
            "expect": "accept",
            "note": note,
            "accept": expect,
        }));
        file
    }
}

fn baseline_stream() -> (Vec<u8>, Dataset) {
    let mut dataset = Dataset::new();
    dataset
        .register_component::<Order>()
        .expect("register Order");
    dataset.append::<Order>(&fixture_rows()).expect("append");
    let mut bytes = Vec::new();
    dataset.write_ipc(&mut bytes).expect("write_ipc");
    (bytes, dataset)
}

/// Re-encode one segment's arrow stream with LZ4 compression.
fn compress_segment(segment_bytes: &[u8]) -> Vec<u8> {
    let reader = StreamReader::try_new(segment_bytes, None).expect("read segment");
    let schema = reader.schema();
    let batches: Vec<RecordBatch> = reader.map(|b| b.expect("batch")).collect();

    let options = IpcWriteOptions::try_new(8, false, MetadataVersion::V5)
        .expect("write options")
        .try_with_compression(Some(CompressionType::LZ4_FRAME))
        .expect("lz4 requires the arrow-ipc lz4 feature");

    let mut out = Vec::new();
    {
        let mut writer = StreamWriter::try_new_with_options(&mut out, &schema, options)
            .expect("compressed writer");
        for batch in &batches {
            writer.write(batch).expect("write compressed batch");
        }
        writer.finish().expect("finish");
    }
    out
}

/// Replace segment `idx`'s body, fixing its length prefix.
fn replace_segment(stream: &[u8], segments: &[Segment], idx: usize, new_body: &[u8]) -> Vec<u8> {
    let seg = &segments[idx];
    let mut out = Vec::with_capacity(stream.len() + new_body.len());
    out.extend_from_slice(&stream[..seg.prefix]);
    out.extend_from_slice(&(new_body.len() as u32).to_le_bytes());
    out.extend_from_slice(new_body);
    out.extend_from_slice(&stream[seg.body + seg.len..]);
    out
}

fn emit(root: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let dir = root.join("packages/arrow-ipc-conformance");
    fs::create_dir_all(dir.join("vectors"))?;

    let (baseline, dataset) = baseline_stream();
    let fingerprint = format!("{:08x}", dataset.schemas().fingerprint());
    let segments = parse_framing(&baseline);
    assert_eq!(segments.len(), 2, "Order plus __alive");
    let order = &segments[0];
    assert_eq!(order.messages.len(), 2, "schema then record batch");
    let schema_msg = &order.messages[0];
    let batch_msg = &order.messages[1];
    assert_eq!(
        schema_msg.header_type, HEADER_SCHEMA,
        "the first message of a segment is its Schema"
    );
    assert_eq!(
        batch_msg.header_type, HEADER_RECORD_BATCH,
        "the second message of a segment is its RecordBatch"
    );
    let order_body = &baseline[order.body..order.body + order.len];
    let rb_table = record_batch_table(order_body, batch_msg);

    let rows = fixture_rows();
    let mut corpus = Corpus {
        dir: dir.clone(),
        cases: Vec::new(),
        host_rejects: 0,
        host_accepts: Vec::new(),
    };

    // ---- accept -----------------------------------------------------------
    let baseline_vector = corpus.accept(
        "baseline",
        "A stream straight out of Dataset::write_ipc. Every codec must accept it \
         and read these values back.",
        baseline.clone(),
        json!({
            "components": ["Order", "__alive"],
            "component": "Order",
            "rows": rows.len(),
            "columns": {
                "id": { "type": "int64", "values": rows.iter().map(|o| o.id).collect::<Vec<_>>() },
                "amount": { "type": "float64", "values": rows.iter().map(|o| o.amount).collect::<Vec<_>>() },
                "currency": { "type": "utf8", "values": rows.iter().map(|o| o.currency.clone()).collect::<Vec<_>>() },
                "valid": { "type": "bool", "values": rows.iter().map(|o| o.valid).collect::<Vec<_>>() },
            }
        }),
    );

    // ---- framing ----------------------------------------------------------
    let mut v = baseline.clone();
    v.extend_from_slice(b"trailing junk");
    corpus.reject(
        "trailing_bytes",
        "trailing_bytes",
        "Bytes follow the zero-length terminator. The stream is complete at the \
         terminator, so anything after it means the producer and consumer \
         disagree about the payload.",
        v,
    );

    let mut v = baseline.clone();
    v.truncate(v.len() - 4);
    corpus.reject(
        "missing_terminator",
        "truncated_stream",
        "The zero-length terminator is absent, so the segment loop runs off the end.",
        v,
    );

    let mut v = baseline.clone();
    // Far past the end of the payload, not merely into the next segment. A small
    // bump would overlap the following segment instead, and then the reason a
    // codec reports would depend on whether it validates framing up front or
    // segment by segment. This way there is one answer.
    let bumped = (baseline.len() + 100_000) as u32;
    v[order.prefix..order.prefix + 4].copy_from_slice(&bumped.to_le_bytes());
    corpus.reject(
        "segment_longer_than_stream",
        "truncated_stream",
        "A segment's declared length runs past the end of the payload.",
        v,
    );

    // A segment whose entire body is an end-of-stream marker: no Schema message.
    let mut v = Vec::new();
    v.extend_from_slice(&8u32.to_le_bytes());
    v.extend_from_slice(&0xFFFF_FFFFu32.to_le_bytes());
    v.extend_from_slice(&0u32.to_le_bytes());
    v.extend_from_slice(&baseline);
    corpus.reject(
        "empty_segment",
        "empty_segment",
        "A segment carrying only an end-of-stream marker declares no component \
         and must be reported as empty rather than as a wrong header type.",
        v,
    );

    let mut v = baseline.clone();
    let cont = order.body + schema_msg.start;
    v[cont..cont + 4].copy_from_slice(&0xDEAD_BEEFu32.to_le_bytes());
    corpus.reject(
        "bad_continuation_marker",
        "bad_continuation",
        "A message must open with 0xFFFFFFFF.",
        v,
    );

    let mut v = baseline.clone();
    let mlen_at = order.body + schema_msg.start + 4;
    v[mlen_at..mlen_at + 4].copy_from_slice(&((order.len + 32) as u32).to_le_bytes());
    corpus.reject(
        "message_longer_than_segment",
        "truncated_message",
        "A message's metadata length runs past the end of its segment.",
        v,
    );

    // Duplicate the record batch message so the segment carries a third message.
    let mut new_body = order_body.to_vec();
    let rb_bytes = order_body[batch_msg.start..batch_msg.end].to_vec();
    // Drop the trailing end-of-stream marker, append the batch again, then
    // restore the marker so only the message count changes.
    new_body.truncate(batch_msg.end);
    new_body.extend_from_slice(&rb_bytes);
    new_body.extend_from_slice(&0xFFFF_FFFFu32.to_le_bytes());
    new_body.extend_from_slice(&0u32.to_le_bytes());
    corpus.reject(
        "extra_message_in_segment",
        "extra_message",
        "A segment carries exactly one Schema and one RecordBatch. A second \
         RecordBatch means the reader would silently ignore data.",
        replace_segment(&baseline, &segments, 0, &new_body),
    );

    // Bytes past a segment's own end-of-stream marker. The other extra_message
    // vector appends a whole second RecordBatch; this one appends only junk, so
    // a codec that stops at the marker without checking the segment is spent
    // fails here and passes there.
    let mut new_body = order_body.to_vec();
    new_body.extend_from_slice(b"junk past the marker");
    corpus.reject(
        "bytes_after_segment_marker",
        "extra_message",
        "A segment is spent once its end-of-stream marker is read. Bytes after \
         it mean the reader would silently drop data.",
        replace_segment(&baseline, &segments, 0, &new_body),
    );

    // ---- message headers --------------------------------------------------
    let mut v = baseline.clone();
    let ht_at = order.body + field(order_body, schema_msg.table, 1).expect("header_type");
    v[ht_at] = HEADER_RECORD_BATCH;
    corpus.reject(
        "first_message_not_schema",
        "first_message_not_schema",
        "A segment opens with its Schema message.",
        v,
    );

    let batch_ht_at = order.body + field(order_body, batch_msg.table, 1).expect("header_type");
    let mut v = baseline.clone();
    v[batch_ht_at] = HEADER_DICTIONARY_BATCH;
    corpus.reject(
        "dictionary_batch",
        "dictionary_batch",
        "Dictionary encoding is outside this format. The refusal names it \
         specifically, because a dictionary batch is a plausible thing for a \
         writer to emit and a confusing thing to diagnose.",
        v,
    );

    let mut v = baseline.clone();
    v[batch_ht_at] = 99;
    corpus.reject(
        "unknown_header_type",
        "second_message_not_record_batch",
        "The second message must be a RecordBatch, and the refusal echoes the \
         header type it actually found.",
        v,
    );

    // ---- record batch metadata -------------------------------------------
    let length_at = order.body + field(order_body, rb_table, 0).expect("RecordBatch.length");
    let mut v = baseline.clone();
    v[length_at..length_at + 8].copy_from_slice(&(-1i64).to_le_bytes());
    corpus.reject(
        "negative_row_count",
        "bad_row_count",
        "A negative declared row count must be refused by the codec, not turned \
         into a native allocation error deeper in.",
        v,
    );

    let mut v = baseline.clone();
    v[length_at..length_at + 8].copy_from_slice(&i64::MAX.to_le_bytes());
    corpus.reject(
        "overflowing_row_count",
        "bad_row_count",
        "A declared row count no allocation could satisfy must be refused up front.",
        v,
    );

    let (nodes_at, node_count) = vector(order_body, rb_table, 1).expect("RecordBatch.nodes");
    let mut v = baseline.clone();
    let count_at = order.body + nodes_at - 4;
    v[count_at..count_at + 4].copy_from_slice(&((node_count - 1) as u32).to_le_bytes());
    corpus.reject(
        "nodes_field_count_mismatch",
        "nodes_field_mismatch",
        "The node count must equal the schema's field count. A short nodes \
         vector means the buffer walk would read another field's buffers.",
        v,
    );

    let (buffers_at, buffer_count) = vector(order_body, rb_table, 2).expect("RecordBatch.buffers");
    let mut v = baseline.clone();
    // Each Buffer is an inline struct of { i64 offset, i64 length }.
    let first_len_at = order.body + buffers_at + 8;
    v[first_len_at..first_len_at + 8].copy_from_slice(&(batch_msg.body_len + 4096).to_le_bytes());
    corpus.reject(
        "buffer_overruns_body",
        "buffer_overruns_body",
        "A buffer whose declared span leaves the message body must be refused \
         before any column is read.",
        v,
    );

    let mut v = baseline.clone();
    let last_len_at = order.body + buffers_at + (buffer_count - 1) * 16 + 8;
    v[last_len_at..last_len_at + 8].copy_from_slice(&(-8i64).to_le_bytes());
    corpus.reject(
        "negative_buffer_length",
        "buffer_overruns_body",
        "A negative buffer length is not a usable span.",
        v,
    );

    // ---- schema metadata --------------------------------------------------
    // Rename the component key in place. Same byte length, so nothing shifts.
    let needle = b"__saci_component";
    let found = baseline
        .windows(needle.len())
        .position(|w| w == needle)
        .expect("component metadata key");
    let mut v = baseline.clone();
    v[found + needle.len() - 1] = b'X';
    corpus.reject(
        "missing_component_key",
        "missing_component_key",
        "A segment without the __saci_component metadata key declares no \
         component, so nothing can address it.",
        v,
    );

    // ---- compression ------------------------------------------------------
    let compressed = compress_segment(order_body);
    corpus.reject(
        "compressed_batch",
        "compressed_batch",
        "A genuinely LZ4-compressed record batch, written by arrow-rs. The \
         format carries no compression, so every codec refuses it rather than \
         reading the compressed bytes as values.",
        replace_segment(&baseline, &segments, 0, &compressed),
    );

    // ---- api level, against the baseline ---------------------------------
    corpus.reject_op(
        "unknown_component",
        "unknown_component",
        "Addressing a component the stream does not carry.",
        &baseline_vector,
        json!({ "kind": "component", "component": "Nope" }),
    );
    corpus.reject_op(
        "unknown_field",
        "unknown_field",
        "Addressing a field the component does not declare.",
        &baseline_vector,
        json!({ "kind": "column", "component": "Order", "field": "nope", "type": "float64" }),
    );
    corpus.reject_op(
        "type_mismatch",
        "type_mismatch",
        "Reading a Float64 column as Int64.",
        &baseline_vector,
        json!({ "kind": "column", "component": "Order", "field": "amount", "type": "int64" }),
    );
    corpus.reject_op(
        "row_out_of_range",
        "row_out_of_range",
        "Writing past the last row.",
        &baseline_vector,
        json!({ "kind": "set", "component": "Order", "field": "usd_amount", "type": "float64", "row": 9_999, "value": 1.0 }),
    );
    corpus.reject_op(
        "variable_width_write",
        "variable_width_write",
        "Writing a Utf8 column in place. Changing a string's length would move \
         every later offset and the buffer lengths in the RecordBatch metadata.",
        &baseline_vector,
        json!({ "kind": "set", "component": "Order", "field": "settlement", "type": "utf8", "row": 0, "value": "X" }),
    );

    // ---- manifest ---------------------------------------------------------
    let reasons: Vec<&str> = {
        let mut seen: Vec<&str> = corpus
            .cases
            .iter()
            .filter_map(|c| c["reason"].as_str())
            .collect();
        seen.sort_unstable();
        seen.dedup();
        seen
    };

    let manifest = json!({
        "format_version": 1,
        "generated_by": GENERATED_BY,
        "component": "Order",
        "schema_fingerprint": fingerprint,
        "reasons": reasons,
        "cases": corpus.cases,
    });

    let manifest_path = dir.join("manifest.json");
    fs::write(
        &manifest_path,
        format!("{}\n", serde_json::to_string_pretty(&manifest)?),
    )?;

    let mut counts: HashMap<&str, usize> = HashMap::new();
    for case in &corpus.cases {
        *counts.entry(case["expect"].as_str().unwrap()).or_default() += 1;
    }
    println!("wrote {}", manifest_path.display());
    println!(
        "cases: {} accept, {} reject",
        counts.get("accept").copied().unwrap_or(0),
        counts.get("reject").copied().unwrap_or(0)
    );
    println!("fingerprint: {fingerprint}");
    println!("node count: {node_count}, buffer count: {buffer_count}");
    println!(
        "rust host reader refuses {} of the reject vectors",
        corpus.host_rejects
    );
    if !corpus.host_accepts.is_empty() {
        // Expected for the checks the codecs add on top of arrow-rs: extra
        // messages, node count, trailing bytes. Listed so a surprising entry
        // here is visible rather than silent.
        println!(
            "arrow-rs itself accepts, codecs must still refuse: {}",
            corpus.host_accepts.join(", ")
        );
    }
    Ok(())
}

fn repo_root() -> PathBuf {
    // CARGO_MANIFEST_DIR is crates/saci-service.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("repo root")
        .to_path_buf()
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let arg = std::env::args().nth(1).unwrap_or_default();
    if arg != "emit" {
        eprintln!(
            "usage: cargo run -p saci-service --features conformance \
             --example conformance_vectors -- emit"
        );
        std::process::exit(2);
    }
    emit(&repo_root())
}
