//! The generated `Order` schema constants.
//!
//! `examples/polyglot/generated/` is regenerated by the `polyglot_schema_emit`
//! example (`examples/polyglot/schema_emit.rs`), a self-contained emitter that
//! owns its own `Order` definition. It is the single source of the schema bytes
//! and the fingerprint every non-Rust stage and plugin embeds as a constant.
//! `quickstart`, `polyglot`-adjacent tooling and `plugins` all depend on it, so
//! each runs this step: a stage compiled against a stale copy fails the host's
//! fingerprint check at load time, with nothing in the failure pointing at the
//! copy.

use std::path::PathBuf;

use crate::sh::{Ctx, Result};

/// The directory the emitter writes into.
pub fn dir(ctx: &Ctx) -> PathBuf {
    ctx.path("examples/polyglot/generated")
}

/// Regenerate the constants and confirm every file the caller compiles in is
/// present, then log the fingerprint they all carry.
///
/// `what` names what is being generated, for the log line. `missing` is the
/// exit code for an emit that produced nothing, which each caller documents.
pub fn emit(ctx: &Ctx, what: &str, required: &[&str], missing: u8) -> Result<()> {
    ctx.log(format!(
        "generating {what} via the polyglot_schema_emit example..."
    ));
    ctx.cargo()?
        .args([
            "run",
            "-p",
            "saci-service",
            "--features",
            "wasm",
            "--example",
            "polyglot_schema_emit",
            "--",
            "emit",
        ])
        .run()?;

    let dir = dir(ctx);
    for file in required {
        let path = dir.join(file);
        if !path.is_file() {
            return ctx.fail(
                missing,
                &[&format!("emit did not produce {}", path.display())],
            );
        }
    }

    let fingerprint = ctx.read(&dir.join("order_fingerprint.txt"))?;
    ctx.log(format!("fingerprint: {}", fingerprint.trim()));
    Ok(())
}
